kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: database-getmodel
  name: database-getmodel
  namespace: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database-getmodel
    spec:
      containers:
        #maven
        - name: getmodel
          image: gmt.reg.me/frame/maven-getmodel
          command:
            - /bin/sh
          args:
            - /workspace/pack.sh
          volumeMounts:
            - name: database-getmodel-pack
              mountPath: /workspace/pack.sh
              subPath: pack.sh
              readOnly: true
            - name: database-getmodel-set
              mountPath: /project/src/main/java/com/app/AppSet.java
              subPath: AppSet.java
              readOnly: true
            - name: database-getmodel-get
              mountPath: /project/src/main/java/com/app/AppGet.java
              subPath: AppGet.java
              readOnly: true
            - name: share-jar
              mountPath: /workspace
        - name: redis1
          image: redis:5
          imagePullPolicy: IfNotPresent
       #server
        - name: server
          image: gmt.reg.me/frame/jn-getmodel
          command:
            - node
          args:
            - /workspace/server.js
          volumeMounts:
            - name: database-getmodel-server
              mountPath: /workspace/server.js
              subPath: server.js
              readOnly: true
            - name: database-getmodel-modelset
              mountPath: /workspace/modelset.sh
              subPath: modelset.sh
              readOnly: true
            - name: database-getmodel-modelget
              mountPath: /workspace/modelget.sh
              subPath: modelget.sh
              readOnly: true
            - name: share-jar
              mountPath: /workspace
            
      volumes:
        - name: database-getmodel-pack
          configMap:
            name: database-getmodel-pack
            defaultMode: 0755
        - name: database-getmodel-set
          configMap:
            name: database-getmodel-set
            defaultMode: 0755
        - name: database-getmodel-get
          configMap:
            name: database-getmodel-get
            defaultMode: 0755
        - name: database-getmodel-server
          configMap:
            name: database-getmodel-server
            defaultMode: 0755
        - name: database-getmodel-modelset
          configMap:
            name: database-getmodel-modelset
            defaultMode: 0755
        - name: database-getmodel-modelget
          configMap:
            name: database-getmodel-modelget
            defaultMode: 0755
        - name: share-jar
          emptyDir: {}
